# Generated by Django 6.0.8 on 2026-08-05 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commercial_name', models.CharField(max_length=200, verbose_name='Nom commercial')),
                ('dci', models.CharField(max_length=200, verbose_name='Dénomination Commune Internationale')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Code-barres')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Fabricant')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Emplacement dans la pharmacie')),
                ('min_stock', models.PositiveIntegerField(default=10, verbose_name='Stock minimum')),
                ('max_stock', models.PositiveIntegerField(default=100, verbose_name='Stock maximum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.category')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['commercial_name'],
                'indexes': [models.Index(fields=['barcode'], name='medicines_m_barcode_ac4d36_idx'), models.Index(fields=['dci'], name='medicines_m_dci_c181fc_idx')],
            },
        ),
    ]
