# Generated by Django 6.0.8 on 2026-08-05 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('received_date', models.DateField(auto_now_add=True)),
                ('purchase_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='medicines.medicine')),
            ],
            options={
                'verbose_name': 'Lot de stock',
                'verbose_name_plural': 'Lots de stock',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=3)),
                ('reason', models.CharField(choices=[('PURCHASE', 'Achat'), ('DONATION', 'Don'), ('RETURN', 'Retour fournisseur'), ('SALE', 'Vente'), ('LOSS', 'Perte'), ('EXPIRATION', 'Expiration'), ('ADJUSTMENT', 'Ajustement inventaire')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='N° commande, vente, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['expiry_date'], name='inventory_s_expiry__cf6e69_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['batch_number'], name='inventory_s_batch_n_41e167_idx'),
        ),
    ]
