# Generated by Django 6.0.8 on 2026-08-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.CharField(max_length=255),
        ),
    ]
