# Generated by Django 6.0.8 on 2026-08-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='devise',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('EUR', 'EUR'), ('USD', 'USD')], default='FCFA', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
