# Generated by Django 6.0.8 on 2026-09-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la pharmacie (PNG, JPG)', null=True, upload_to='logos/')),
                ('site_name', models.CharField(default='DENG PHARMA', help_text='Nom du site', max_length=100)),
                ('slogan', models.CharField(blank=True, default='Pharmacie intelligente', help_text='Slogan du site', max_length=200)),
                ('phone', models.CharField(blank=True, default='+235 XX XX XX XX', help_text='Numéro de téléphone', max_length=20)),
                ('address', models.CharField(blank=True, default="N'Djaména, Tchad", help_text='Adresse de la pharmacie', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
